### ISSUE TITLE
Sol Heredit moves toward/with player too quickly

### ISSUE THREAD

**Issue by kjholt** [farteronline/battle-sim#1]
After moving back to dodge an attack, Sol moves toward the player whereas in the fight you have time to move back toward him for a tick or two before he does that, right?

**Comment by farteronline** [comment]
good catch. it is functionally equivalent due to update orders, but its good to also be visually accurate, so I will work on this.

In game sols movement is calculated earlier in the tick than the player, whereas my sim the players movement is calculated first. So to have sol move correctly, he has to visually be 1t ahead. Functionally it will result in the same combat, but I should fix this so sol moves first each tick, allowing for visual accuracy.

**Comment by farteronline** [comment]
should be fixed now

**Comment by kjholt** [comment]
Sorry, it still seems incorrect to me. To be clear, in-game Sol doesn't immediately move toward the player when the player moves back to dodge a spear or shield attack. The player has a tick after the spear/shield attack to move back into Sol's melee range while he stands in place for that tick. But in the simulator he moves toward the player's position right away so you're essentially kiting around the arena while dodging. Unless I'm doing something wrong which I concede is always a high possibility.

**Comment by kjholt** [comment]
Ah I see what the problem was now. I was mistakenly seeing the "dust" tick as the tick where he attacks rather than the one right before that. So disregard the above! Thanks :)
